# Generated by Django 5.0.4 on 2026-03-26 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('description', models.TextField()),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('duration_hours', models.PositiveIntegerField(default=0)),
                ('max_group_size', models.PositiveIntegerField(default=15)),
                ('languages', models.CharField(default='English, Bangla', max_length=200)),
                ('highlights', models.JSONField(default=list)),
                ('included', models.JSONField(default=list)),
                ('excluded', models.JSONField(default=list)),
                ('currency', models.CharField(choices=[('BDT', 'Taka'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='BDT', max_length=3)),
                ('price_adult', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_child', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_infant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('thumbnail', models.ImageField(upload_to='tours/thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='destinations.destination')),
            ],
            options={
                'db_table': 'tours',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tours/itinerary/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='tours.tour')),
            ],
            options={
                'db_table': 'tour_itinerary',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_cancellation_hours', models.PositiveIntegerField(default=24, help_text='Hours before tour start for free cancellation')),
                ('partial_refund_percent', models.PositiveIntegerField(default=50)),
                ('partial_refund_hours', models.PositiveIntegerField(default=12, help_text='Hours before tour start for partial refund')),
                ('description', models.TextField(blank=True)),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policy', to='tours.tour')),
            ],
            options={
                'db_table': 'cancellation_policies',
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tour')),
            ],
            options={
                'db_table': 'tour_images',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['destination', 'is_active'], name='tours_destina_a5c02c_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['is_featured', 'is_active'], name='tours_is_feat_739d3f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itinerary',
            unique_together={('tour', 'day')},
        ),
    ]
