# Generated by Django 5.0.4 on 2026-03-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='booking_cutoff_days',
            field=models.PositiveIntegerField(default=1, help_text='Hide availability within this many days from today'),
        ),
    ]
