# Generated by Django 5.0.4 on 2026-03-26 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='cutoff_hours',
        ),
    ]
