# Generated by Django 5.0.4 on 2026-03-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='destination',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/thumbnails/'),
        ),
    ]
