# Generated by Django 5.0.4 on 2026-04-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_is_featured_alter_destination_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='destination_type',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], db_index=True, default='domestic', max_length=15),
        ),
    ]
